language: java
matrix:
  include:
    - jdk: oraclejdk8

script: >-
    ./config/travis/run-checks.sh &&
    ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V &&
    travis_retry ./gradlew clean headless allTests coverage coveralls

before_install:
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"

addons:
  apt:
    packages:
      - oracle-java8-installer
